[2023-07-08T11:10:58.168+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: assignment.get_departed_flights_from_cdg manual__2023-07-08T11:10:57.178271+00:00 [queued]>
[2023-07-08T11:10:58.186+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: assignment.get_departed_flights_from_cdg manual__2023-07-08T11:10:57.178271+00:00 [queued]>
[2023-07-08T11:10:58.186+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-08T11:10:58.249+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): get_departed_flights_from_cdg> on 2023-07-08 11:10:57.178271+00:00
[2023-07-08T11:10:58.260+0000] {standard_task_runner.py:57} INFO - Started process 586 to run task
[2023-07-08T11:10:58.266+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'get_departed_flights_from_cdg', 'manual__2023-07-08T11:10:57.178271+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpnfzsev7h']
[2023-07-08T11:10:58.267+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask get_departed_flights_from_cdg
[2023-07-08T11:10:58.370+0000] {task_command.py:410} INFO - Running <TaskInstance: assignment.get_departed_flights_from_cdg manual__2023-07-08T11:10:57.178271+00:00 [running]> on host da250f106141
[2023-07-08T11:10:58.520+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='assignment' AIRFLOW_CTX_TASK_ID='get_departed_flights_from_cdg' AIRFLOW_CTX_EXECUTION_DATE='2023-07-08T11:10:57.178271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-08T11:10:57.178271+00:00'
[2023-07-08T11:10:58.904+0000] {logging_mixin.py:149} INFO - heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrrrrreeeeeeeeeeeeeeeeeeeeeeeeeeeee
[2023-07-08T11:10:58.905+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 76, in get_departed_flights_from_cdg
    'departures_list': json.loads(departures),
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
[2023-07-08T11:10:58.920+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=assignment, task_id=get_departed_flights_from_cdg, execution_date=20230708T111057, start_date=20230708T111058, end_date=20230708T111058
[2023-07-08T11:10:58.941+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 59 for task get_departed_flights_from_cdg (the JSON object must be str, bytes or bytearray, not list; 586)
[2023-07-08T11:10:58.961+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-08T11:10:58.991+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
